### ISSUE TITLE
Bug - Default attribute on skill

### ISSUE THREAD

**Issue by Kariaudhanaur** [superseva/mutant-year-zero#108]
When I launched my game, it was ok for my players... but after a while (and some clics), some of the skills became like this : 
![image](https://github.com/superseva/mutant-year-zero/assets/92259502/5189ac1b-bfd6-4ef5-975f-8e3591d946c6)

It's impossible to roll when it's like that, and I didn't figure how to fix this...
In the dropdown list it's still the list of the 4 attributes

Don't know if it's clear...

**Comment by Kariaudhanaur** [comment]
When I created this, I was on "my active world", on Genlab Alpha. But now : 

I switched my Foundry in English. New world. No module.
![image](https://github.com/superseva/mutant-year-zero/assets/92259502/37518166-6f46-432e-a6aa-a57a0a292377)

In the skills compendium, I have only "strength" or "servos" for the skills ... No other attribute.
![image](https://github.com/superseva/mutant-year-zero/assets/92259502/71b9947f-f424-4ea7-84ca-ee2a6b572c36)

I don't know how, but I guess this is why I have issues...

**Comment by PlagaMutant** [comment]
Hi, Have the same problem.

When Editing any skill to open the window and then close the window, the skill broke and attribute turns into MYZ.

Foundry Version installed: 12
Mutant year zero 12.0.0

I tried with only game system installed without addons, and with the Mutant year zero official installed. I tried all combination with or without addons and modules and creating new worlds.

I think the problem is when the pop up window with skill description close.

If anyone can help 

thanks in advance!!!

![foto edit 1](https://github.com/superseva/mutant-year-zero/assets/174129846/77611a94-dd92-4d0f-9e7b-0cc351a65b2a)

![foto edit 2](https://github.com/superseva/mutant-year-zero/assets/174129846/e01b95ac-e25d-4ef5-bf8b-baabfbfc6e7c)

![foto edit 3](https://github.com/superseva/mutant-year-zero/assets/174129846/a17a5b68-d8c3-4742-9f10-56cd485c3dfa)

Other sheet bug is with the ark sheet. Can't use the complete button. Before it works as can see in the image. Thanks again

![arca edit](https://github.com/superseva/mutant-year-zero/assets/174129846/4ef7f640-4041-4b29-a1a4-401b2ac090e6)

**Comment by superseva** [comment]
Thanks for reporting this.
Th skill bug should be fixed now
V12.0.1
You would probably need to edit the skill again and assign the attribute again

I'll deal with the ARK tomorrow

**Comment by PlagaMutant** [comment]
Thanks a lot! It really Works

Every skill its working fine now

Thank you so much! and thanks for fixing it so quickly 

I can’t wait for your magic for the ark Sheet!

**Comment by Kariaudhanaur** [comment]
Ok for me too ! Thank you

**Comment by Kariaudhanaur** [comment]
Hello ! It's still not ok with the Ark sheet... 
Just in case you thought it was fixed :)
Good day !

**Comment by superseva** [comment]
I haven't fix it yet. it's really busy over here so I can't give you estimate

**Comment by superseva** [comment]
**Mutant Year Zero - Version 12.0.2**
Finally...
You know what it was... remnant from v8 that was hidden and ignored until v12 :)
anyhow, the Ark should be working now, someone please check Elder's pulse

**Comment by Kariaudhanaur** [comment]
It's working, thank you!
